preferWorkspacePackages: true
linkWorkspacePackages: true
packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: false
  nx: true
  sharp: true
minimumReleaseAgeExclude:
  - "cli-testing-library@4.0.0"