name: Tests

on:
  push:
    branches: [main, alpha, beta, rc]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: ./.github/actions/setup-tools
      - name: Run Checks
        run: pnpm run test:pr --parallel=3
